apiVersion: v1
kind: Service
metadata:
  name: kavach-web
  namespace: default
  labels:
    app: kavach-web
spec:
  selector:
    app: kavach-web
  type: NodePort
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000