apiVersion: apps/v1
kind: Deployment
metadata:
  name: kavach-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kavach-web
      version: "v1"
  template:
    metadata:
      labels:
        app: kavach-web
        version: "v1"
    spec:
      containers:
      - name: kavach-web-app
        image: factly/kavach-web:0.1.1
        env:
        - name: REACT_APP_API_URL
          value: http://127.0.0.1:4455/.factly/identity/server
        - name: REACT_APP_KRATOS_PUBLIC_URL
          value: http://127.0.0.1:4455/.ory/kratos/public
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
